apiVersion: v1
kind: Service
metadata:
  name: heating-service
spec:
  type: ClusterIP
  selector:
    app: heating
  ports:
    - protocol: TCP
      port: 3001 # the port on which the service is listening
      targetPort: 3000 # the port on which the container is listening

# because the service is of type ClusterIP, it is only accessible from within the cluster
# to access it from outside the cluster, we need to run "kubectl port-forward svc/heating-service 3001:3001 &"
# and then access it from the browser at http://localhost:3001

# to stop the port forwarding, run "fg" to bring the process to the foreground, then press Ctrl+C
# or run "jobs" to see the running jobs, then run "kill %1" to kill the first job