apiVersion: v1
kind: Service
metadata:
  name: status-service
spec:
  selector:
    app: status
  ports:
    - protocol: TCP
      port: 3002 # the port on which the service is listening
      targetPort: 3000 # the port on which the container is listening

  type: LoadBalancer

